### PR TITLE
Add Involution3d

### PR DESCRIPTION
**Pull request by Dootmaan**
Hi there, thank you for your work. I borrowed some codes from https://github.com/f-dangel/unfoldNd and implemented the 3d version of Involution. The original unfoldNd only supports python3.6+, but I found your code could work with lower version of python so i just copyed the unfoldNd folder and did some changes to make it runnable on a lower version of Python. The codes are tested with a 3D UNet on Python 3.5.

### CODE REVIEW

**Comment by ChristophReich1996** [comment]
Hey, @Dootmaan very nice work :) However, I have two concerns, first how memory-efficient is the 3D implementation? Because, as mentioned in the README, the pure PyTorch in 2D is not very memory-efficient, to be honest. The second concern is about the dependence on the [unfoldNd](https://github.com/f-dangel/unfoldNd) implementation. A possible solution could be to call unfold multiple times as suggested [here](https://discuss.pytorch.org/t/how-to-extract-smaller-image-patches-3d/16837).

3D [unfold](https://pytorch.org/docs/stable/tensors.html?highlight=unfold#torch.Tensor.unfold) example with a kernel size of 3 X 3 X 3 and a stride of 1.
```python
import torch
tensor = torch.rand(4, 6, 32, 32, 32)
tensor = tensor.unfold(dimension=2, size=3, step=1).unfold(dimension=3, size=3, step=1).unfold(dimension=4, size=3, step=1)
tensor  = tensor.flatten(start_dim=2, end_dim=4) # [4, 6, 27000, 3, 3, 3]
```

Cheers
Christoph

**Comment by Dootmaan** [comment]
Danke XD. Well about the memory-efficient problem honestly i did not test it with the official implementation. The official implementation is difficult to be integrated into many existing models so i actually likes your pure pytorch implementation a lot. The 3d version mainly follows your 2d implementation. I think the code will look prettier if the unfold3d also Inherit torch.nn.Module so i introduced [unfoldNd](https://github.com/f-dangel/unfoldNd), but actually the dependence of unfoldNd do can be reduced and im planning on spending some time working on it.

**Comment by ChristophReich1996** [comment]
Hey @Dootmaan thanks again, but I guess there are still some issues with your changes. First, I don't think a separate class is needed for the 3D unfold operation. Simply calling unfold on the tensor should be enough. Second, the type hints are somewhat off in your implementation. Finally, the `__repr__()` method needs a revisit. It would also be cool if you can add my latest changes.

**Comment by memmelma** [comment]
Hi @ChristophReich1996 and @Dootmaan, this clould be a possible implementation of the 3D involution.
```python
class Involution3d(nn.Module):
    """
    This class implements the 3d involution.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 sigma_mapping: nn.Module = None,
                 kernel_size: Union[int, Tuple[int, int, int]] = (7, 7, 7),
                 stride: Union[int, Tuple[int, int, int]] = (1, 1, 1),
                 groups: int = 1,
                 reduce_ratio: int = 1,
                 dilation: Union[int, Tuple[int, int, int]] = (1, 1, 1),
                 padding: Union[int, Tuple[int, int, int]] = (3, 3, 3),
                 bias: bool = False,
                 **kwargs) -> None:
        """
        Constructor method
        :param in_channels: (int) Number of input channels
        :param out_channels: (int) Number of output channels
        :param sigma_mapping: (nn.Module) Non-linear mapping as introduced in the paper. If none BN + ReLU is utilized
        :param kernel_size: (Union[int, Tuple[int, int, int]]) Kernel size to be used
        :param stride: (Union[int, Tuple[int, int, int]]) Stride factor to be utilized
        :param groups: (int) Number of groups to be employed
        :param reduce_ratio: (int) Reduce ration of involution channels
        :param dilation: (Union[int, Tuple[int, int, int]]) Dilation in unfold to be employed
        :param padding: (Union[int, Tuple[int, int, int]]) Padding to be used in unfold operation
        :param bias: (bool) If true bias is utilized in each convolution layer
        :param **kwargs: Unused additional key word arguments
        """
        # Call super constructor
        super(Involution3d, self).__init__()
        # Check parameters
        assert isinstance(in_channels, int) and in_channels > 0, "in channels must be a positive integer."
        assert in_channels % groups == 0, "out_channels must be divisible by groups"
        assert isinstance(out_channels, int) and out_channels > 0, "out channels must be a positive integer."
        assert out_channels % groups == 0, "out_channels must be divisible by groups"
        assert isinstance(sigma_mapping, nn.Module) or sigma_mapping is None, \
            "Sigma mapping must be an nn.Module or None to utilize the default mapping (BN + ReLU)."
        assert isinstance(kernel_size, int) or isinstance(kernel_size, tuple), \
            "kernel size must be an int or a tuple of ints."
        assert isinstance(stride, int) or isinstance(stride, tuple), \
            "stride must be an int or a tuple of ints."
        assert isinstance(groups, int), "groups must be a positive integer."
        assert isinstance(reduce_ratio, int) and reduce_ratio > 0, "reduce ratio must be a positive integer."
        assert isinstance(dilation, int) or isinstance(dilation, tuple), \
            "dilation must be an int or a tuple of ints."
        assert isinstance(padding, int) or isinstance(padding, tuple), \
            "padding must be an int or a tuple of ints."
        assert isinstance(bias, bool), "bias must be a bool"
        # Save parameters
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size if isinstance(kernel_size, tuple) else (kernel_size, kernel_size, kernel_size)
        self.stride = stride if isinstance(stride, tuple) else (stride, stride, stride)
        self.groups = groups
        self.reduce_ratio = reduce_ratio
        self.dilation = dilation if isinstance(dilation, tuple) else (dilation, dilation, dilation)
        self.padding = padding if isinstance(padding, tuple) else (padding, padding, padding)
        self.bias = bias
        # Init modules
        self.sigma_mapping = sigma_mapping if sigma_mapping is not None else nn.Sequential(
            nn.BatchNorm3d(num_features=self.out_channels // self.reduce_ratio, momentum=0.3), nn.ReLU())
        self.initial_mapping = nn.Conv3d(
            in_channels=self.in_channels, out_channels=self.out_channels,
            kernel_size=(1, 1, 1), stride=(1, 1, 1), padding=(0, 0, 0),
            bias=bias) if self.in_channels != self.out_channels else nn.Identity()
        self.o_mapping = nn.AvgPool3d(kernel_size=self.stride, stride=self.stride)
        self.reduce_mapping = nn.Conv3d(
            in_channels=self.in_channels,
            out_channels=self.out_channels // self.reduce_ratio, kernel_size=(1, 1, 1),
            stride=(1, 1, 1), padding=(0, 0, 0), bias=bias)
        self.span_mapping = nn.Conv3d(
            in_channels=self.out_channels // self.reduce_ratio,
            out_channels=self.kernel_size[0] * self.kernel_size[1] * self.kernel_size[2] * self.groups,
            kernel_size=(1, 1, 1), stride=(1, 1, 1), padding=(0, 0, 0), bias=bias)
        self.pad = nn.ConstantPad3d(padding=(self.padding[0], self.padding[0],
                                             self.padding[1], self.padding[1],
                                             self.padding[2], self.padding[2]), value=0.)

    def __repr__(self) -> str:
        """
        Method returns information about the module
        :return: (str) Info string
        """
        return ("{}({}, {}, kernel_size=({}, {}, {}), stride=({}, {}, {}), padding=({}, {}, {}), "
                "groups={}, reduce_ratio={}, dilation=({}, {}, {}), bias={}, sigma_mapping={})".format(
            self.__class__.__name__,
            self.in_channels,
            self.out_channels,
            self.kernel_size[0],
            self.kernel_size[1],
            self.kernel_size[2],
            self.stride[0],
            self.stride[1],
            self.stride[2],
            self.padding[0],
            self.padding[1],
            self.padding[2],
            self.groups,
            self.reduce_mapping,
            self.dilation[0],
            self.dilation[1],
            self.dilation[2],
            self.bias,
            str(self.sigma_mapping)
        ))

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        """
        Forward pass
        :param input: (torch.Tensor) Input tensor of the shape [batch size, in channels, height, width]
        :return: (torch.Tensor) Output tensor of the shape [batch size, out channels, height, width] (w/ same padding)
        """
        # Check input dimension of input tensor
        assert input.ndimension() == 5, \
            "Input tensor to involution must be 5d but {}d tensor is given".format(input.ndimension())
        # Save input shape
        batch_size, in_channels, height, width, depth = input.shape
        # Unfold and reshape input tensor
        input_initial = self.initial_mapping(input)
        input_unfolded = self.pad(input_initial) \
            .unfold(dimension=2, size=self.kernel_size[0], step=self.stride[0]) \
            .unfold(dimension=3, size=self.kernel_size[1], step=self.stride[1]) \
            .unfold(dimension=4, size=self.kernel_size[2], step=self.stride[2])
        input_unfolded = input_unfolded.reshape(batch_size, self.groups, self.out_channels // self.groups,
                                                self.kernel_size[0] * self.kernel_size[1] * self.kernel_size[2],
                                                height, width, depth)
        # Generate kernel
        kernel = self.span_mapping(self.sigma_mapping(self.reduce_mapping(self.o_mapping(input))))
        kernel = kernel.view(
            batch_size, self.groups, self.kernel_size[0] * self.kernel_size[1] * self.kernel_size[2],
            height, width, depth).unsqueeze(dim=2)
        # Apply kernel to produce output
        output = (kernel * input_unfolded).sum(dim=3).view(batch_size, -1, height, width, depth)
        return output
```

**Comment by ChristophReich1996** [comment]
Hey @memmelma, this looks very good! Thanks for your contribution, feel free to open a separate pull request, so that I can merge your implementation :)

**Pull request closed without merging**
